resale_flat:
  outputs:
    dev:
      dataset: resale
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/darwin/NTU PACE Data Science Cohort 3/my-project-dsai-3-9c170967ea0e.json # Use your path of key file
      location: US
      method: service-account
      priority: interactive
      project: my-project-dsai-3 # enter your google project id
      threads: 1
      type: bigquery
  target: dev